### ISSUE TITLE
仅仅反应一个kcptun+udp2raw的使用现象，供大家参考

### ISSUE THREAD

**Issue by Se7enMuting** [wangyu-/udp2raw#111]
最近好像比较流行 科*上网+kcptun+udp2raw 这个加速套路。
我用下来发现套不套udp2raw对网速还是有明显影响的。我套了udp2raw，发现kcptun的消耗量是3-4倍，而不套udp2raw，单单kcptun的消耗量是2倍左右（意思是：油管的流量x2=路由实际下载流量），大家是什么情况啊？
Server是美西的。不知道能不能通过udp2raw的参数优化这个现象，还是这个只是我的个例现象......
还有一个小问题，因为路由器负载的问题，我科学这端有加密，尾端udp2raw如果不加密（或者弱加密）有什么影响吗？

**Comment by wangyu-** [comment]
贴出参数、流量消耗的统计方法、具体的数据。

https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看

**Comment by Justsoos** [comment]
2 raw socket 这种用法，本身就消耗大量cpu和底层驱动之间对话成本的，你先不用看客户端了，先看看你的 vps 服务器能不能支持高流量下网络协议 raw 的消耗，尤其是那些便宜 vps。

按原理说，如果底层驱动造成协议栈（算法）延迟 -- 相当于增加了网络延迟，kcp 的确会加大重复丢包率，这也许就是 raw 应用的一个最大瓶颈吧，我觉得更高级的发展方向，还是要看 quic 在超长管道里塞满包的协议算法，kcp 和 2raw 在算法上配合有负面正反馈。

**Comment by vbzc** [comment]
> 2 raw socket 这种用法，本身就消耗大量cpu和底层驱动之间对话成本的，你先不用看客户端了，先看看你的 vps 服务器能不能支持高流量下网络协议 raw 的消耗，尤其是那些便宜 vps。
> 
> 按原理说，如果底层驱动造成协议栈（算法）延迟 -- 相当于增加了网络延迟，kcp 的确会加大重复丢包率，这也许就是 raw 应用的一个最大瓶颈吧，我觉得更高级的发展方向，还是要看 quic 在超长管道里塞满包的协议算法，kcp 和 2raw 在算法上配合有负面正反馈。

你好 请问如何判断 vps 服务器能不能支持高流量下网络协议 raw 的消耗 呀？谢谢
