### ISSUE TITLE
feature request: support bind address/port on server - remote socket

### ISSUE THREAD

**Issue by Jimmy-Z** [wangyu-/udp2raw#354]
I'm trying to use L2TP on top of udp2raw, which requires remote addr/port to be specified on both end.

I know I could simply using openvpn, where server doesn't need to know client address/port, just trying to squeeze more performance out of my potato router.

**Comment by wangyu-** [comment]
I have tested udp2raw +l2tp before, I can confirm it already works without the feature, at least with my configuration.

**Comment by Jimmy-Z** [comment]
I meant static/v3/unmanaged/bare L2TP without IPSec.

https://man7.org/linux/man-pages/man8/ip-l2tp.8.html

**Comment by Jimmy-Z** [comment]
I later realized udp2raw supports multiple clients so this is a big change and probably not intended use case, so I'll close this.
